In [ ]:
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)
  
class Child(Greeter):
    def __init__(self, name):
      Greeter.__init__(self,name)
      print(name + "나는 지식입니다.")

In [ ]:
a = Greeter("test")
a.name

'test'

In [ ]:
c = Child("테스트")
c.greet

테스트나는 지식입니다.


<bound method Greeter.greet of <__main__.Child object at 0x7fdeb7d2e450>>

In [ ]:
import numpy as np

In [ ]:
a = np.array([0,1,2,3])
print(np.all(a))   # 모든 값이 0 0 아닐 때 True
print(np.all(a>1)) # all 모든 조건이 맞을 때 True

False
False


In [ ]:
print(np.any(a))  # 0 아닌 값이 1개라도 있으면 True
print(np.any(a>2)) # 조건에 부합하는 값이 1개라도 있으면 True

True
True


In [ ]:
b = np.array([1, 0, np.nan, np.inf])
print(np.isnan(b))    # 넘파이 통해 nan 을 찾아내는법 / nan 숫자가 아닌 값 누락값이 왜 발생하는가?

[False False  True False]


In [ ]:
c = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print(np.iscomplex(c))    # 복소수 판별법
print(np.isreal(c))   # 실수 판별법

[ True False False False False  True]
[False  True  True  True  True False]


In [ ]:
# print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))
# print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
# print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
a1 = np.array([1,3,4,5,7])
a2 = np.array([1,3,4,5,7])
a3 = np.array([1,3,4.00001,5,7])
# np.allclose(a2, a3, rtol=1e-05, atol=1e-08, equal_nan=False)
# np.allclose(a1,a3, equal_nan=True) # allclose는 매우 작은 양의 공차는 오차로 인정
np.array_equal(a1,a3)          # array_equal 완전히 같아야

False

In [ ]:
one = np.ones(10)*7
print(one)

[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]


In [ ]:
e = np.identity(2)   #단위행렬 생성
print(e)

[[1. 0.]
 [0. 1.]]


In [ ]:
rand_num = np.random.normal(0,1,5)   # 평균 0 표준편차 1에서 랜덤 5개 표본 추출 
print(rand_num)

[ 1.62992607  0.0103201  -0.55226461 -0.81359486  0.73117342]


In [ ]:
f= np.arange(30,71,2)
print(f)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
f = np.arange(1,13).reshape(3,4)
for i in np.nditer(f):
  print(i, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [ ]:
# 22번 
a = np.arange(21)
print(a)
a[(a >= 9) &(a <= 15)] *= -1  
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [ ]:
#랜덤으로 픽 
a = np.random.randint(0,11,5)
print(a)

[ 6  1  9 10  6]


In [ ]:
# 그냥 값끼리 곱
a = np.array([1,2,3,4])
b = np.random.randint(0,11,4)
print(a)
print(b)
print(a*b)

[1 2 3 4]
[ 0 10  0  2]
[ 0 20  0  8]


In [ ]:
a = np.arange(10,22).reshape(3,4)
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [ ]:
a = np.ones((10,10))
print(a)
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
x = np.diag([1,2,3,4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
c = np.zeros((4,4))
print(c)
c[::2,1::2]=1
c[1::2,::2]=1
print(c)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [ ]:
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 1, 0])
print(m+v)

[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]


In [ ]:
# 35번 ?